---
title: "writing functions"
author: "Yuning Wang"
date: "10/24/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)
library(ggridges)

set.seed(1)
```

## Get started

write some functions

```{r}
x = rnorm(n = 30, mean = 4, sd = 2.3)
x_again = rnorm(n = 30, mean = 6, sd = .3)
y = rnorm(n = 25, mean = 5, sd = 3)

(x - mean(x)) / sd(x)
(x_again - mean(x_again)) / sd(x_again)
```

Now a function

```{r}
z_score = function(x) {
  
  if(!is.numeric(x)){
    stop("x should be numeric")
  } else if (length(x) == 1) {
    stop("Z scores cannot be computed for length 1 vectors")
  }
  
  z = (x - mean(x)) / sd(x)
  z
}
```

Try out the function

```{r error=TRUE}
z_score(x = y)
z_score(x_again)

z_score(x = 3)
z_score("my name is jeff")
z_score(sample(c(TRUE, FALSE), 25, replace = TRUE))
z_score(c(T, T, F, F))

z_score(x = iris)
```

### Multiple outputs

```{r}
mean_and_sd = function(input_x) {
  
  if (!is.numeric(input_x)) {
    stop("Argument x should be numeric")
  } else if (length(input_x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(input_x)
  sd_x = sd(input_x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

test this function

```{r}
mean_and_sd(input_x =  y)
```

### Multiple Inputs

```{r}
sim_data = tibble(
  x = rnorm(30, mean = 1, sd = 1),
  y = 2 + 3 * x + rnorm(30, 0, 1)
)

sim_data %>% ggplot(aes(x = x, y = y)) + geom_point()

ls_fit = lm(y ~ x, data = sim_data)
  
beta0_hat = coef(ls_fit)[1]
beta1_hat = coef(ls_fit)[2]
```

```{r}
sim_regression = function(n, beta0, beta1){
  
  sim_data = tibble(
  x = rnorm(n, mean = 1, sd = 1),
  y = beta0 + beta1 * x + rnorm(n, 0, 1)
)


ls_fit = lm(y ~ x, data = sim_data)

tibble(
  # the intercept  
  beta0_hat = coef(ls_fit)[1],
  # the slope
  beta1_hat = coef(ls_fit)[2])
}

sim_regression(n = 3000, beta0 = 17, beta1 = 3)

sim_regression(3000, 17, 3)
```


## Scrape lots of napoleon

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-title") %>%
  html_text()

review_stars = dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = dynamite_html %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```

now as a function

```{r}
read_page_reviews <- function(page_url) {
  
  h = read_html(page_url)
  
  review_titles = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  review_stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  review_text = h %>%
    html_nodes(".review-data:nth-child(4)") %>%
    html_text()
  
  tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )
  
}
```

```{r}
read_page_reviews("https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=3")
```



